package com.jotase.crystalsystem.models;
// Generated Jul 15, 2015 1:51:53 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BudgetId generated by hbm2java
 */
@Embeddable
public class BudgetId  implements java.io.Serializable {


     private int id;
     private int customersId;

    public BudgetId() {
    }

    public BudgetId(int id, int customersId) {
       this.id = id;
       this.customersId = customersId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="customers_id", nullable=false)
    public int getCustomersId() {
        return this.customersId;
    }
    
    public void setCustomersId(int customersId) {
        this.customersId = customersId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BudgetId) ) return false;
		 BudgetId castOther = ( BudgetId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getCustomersId()==castOther.getCustomersId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getCustomersId();
         return result;
   }   


}


