package com.jotase.crystalsystem.models;
// Generated Jul 4, 2015 1:37:22 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Budget generated by hbm2java
 */
@Entity
@Table(name="budget"
    ,catalog="cristal"
    , uniqueConstraints = @UniqueConstraint(columnNames="invoice") 
)
public class Budget  implements java.io.Serializable {


    
     private BudgetId id;
    @NotNull (message = "Debe seleccionar un cliente")
     private Costumers costumers;
    @NotNull (message = "No se ha calculado el subtotal")
     private double subtotal;
    @NotNull (message = "No se ha calculado el total")
     private double total;
     private Date date;
     private Date finishDate;
     private String invoice;
     @NotNull (message = "Debe tener al menos una orden")
     private Set orderglasses = new HashSet(0);

    public Budget() {
    }

	
    public Budget(BudgetId id, Costumers costumers, double subtotal, double total, Date date) {
        this.id = id;
        this.costumers = costumers;
        this.subtotal = subtotal;
        this.total = total;
        this.date = date;
    }
    public Budget(BudgetId id, Costumers costumers, double subtotal, double total, Date date, Date finishDate, String invoice, Set orderglasses) {
       this.id = id;
       this.costumers = costumers;
       this.subtotal = subtotal;
       this.total = total;
       this.date = date;
       this.finishDate = finishDate;
       this.invoice = invoice;
       this.orderglasses = orderglasses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="costumersId", column=@Column(name="costumers_id", nullable=false) ) } )
    public BudgetId getId() {
        return this.id;
    }
    
    public void setId(BudgetId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="costumers_id", nullable=false, insertable=false, updatable=false)
    public Costumers getCostumers() {
        return this.costumers;
    }
    
    public void setCostumers(Costumers costumers) {
        this.costumers = costumers;
    }

    
    @Column(name="subtotal", nullable=false, precision=22, scale=0)
    public double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }

    
    @Column(name="total", nullable=false, precision=22, scale=0)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="finishDate", length=10)
    public Date getFinishDate() {
        return this.finishDate;
    }
    
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    
    @Column(name="invoice", unique=true, length=45)
    public String getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(String invoice) {
        this.invoice = invoice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="budget")
    public Set getOrderglasses() {
        return this.orderglasses;
    }
    
    public void setOrderglasses(Set orderglasses) {
        this.orderglasses = orderglasses;
    }




}


