package com.jotase.crystalsystem.models;
// Generated Jul 4, 2015 1:37:22 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BudgetId generated by hbm2java
 */
@Embeddable
public class BudgetId  implements java.io.Serializable {


     private int id;
     private int costumersId;

    public BudgetId() {
    }

    public BudgetId(int id, int costumersId) {
       this.id = id;
       this.costumersId = costumersId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="costumers_id", nullable=false)
    public int getCostumersId() {
        return this.costumersId;
    }
    
    public void setCostumersId(int costumersId) {
        this.costumersId = costumersId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BudgetId) ) return false;
		 BudgetId castOther = ( BudgetId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getCostumersId()==castOther.getCostumersId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getCostumersId();
         return result;
   }   


}


