package com.jotase.crystalsystem.models;
// Generated Jul 15, 2015 1:51:53 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Budget generated by hbm2java
 */
@Entity
@Table(name="budget"
    ,catalog="cristal"
    , uniqueConstraints = @UniqueConstraint(columnNames="invoice") 
)
public class Budget  implements java.io.Serializable {


     private BudgetId id;
     private Customers customers;
     private double subtotal;
     private double total;
     private Date deadline;
     private Date date;
     private Date finishDate;
     private String invoice;
     private Set orderglasses = new HashSet(0);

    public Budget() {
    }

	
    public Budget(BudgetId id, Customers customers, double subtotal, double total, Date deadline, Date date) {
        this.id = id;
        this.customers = customers;
        this.subtotal = subtotal;
        this.total = total;
        this.deadline = deadline;
        this.date = date;
    }
    public Budget(BudgetId id, Customers customers, double subtotal, double total, Date deadline, Date date, Date finishDate, String invoice, Set orderglasses) {
       this.id = id;
       this.customers = customers;
       this.subtotal = subtotal;
       this.total = total;
       this.deadline = deadline;
       this.date = date;
       this.finishDate = finishDate;
       this.invoice = invoice;
       this.orderglasses = orderglasses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="customersId", column=@Column(name="customers_id", nullable=false) ) } )
    public BudgetId getId() {
        return this.id;
    }
    
    public void setId(BudgetId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customers_id", nullable=false, insertable=false, updatable=false)
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    
    @Column(name="subtotal", nullable=false, precision=22, scale=0)
    public double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }

    
    @Column(name="total", nullable=false, precision=22, scale=0)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="deadline", nullable=false, length=10)
    public Date getDeadline() {
        return this.deadline;
    }
    
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="finishDate", length=10)
    public Date getFinishDate() {
        return this.finishDate;
    }
    
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    
    @Column(name="invoice", unique=true, length=45)
    public String getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(String invoice) {
        this.invoice = invoice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="budget")
    public Set getOrderglasses() {
        return this.orderglasses;
    }
    
    public void setOrderglasses(Set orderglasses) {
        this.orderglasses = orderglasses;
    }




}


