package com.jotase.crystalsystem.models;
// Generated Jul 4, 2015 1:37:22 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GlassesId generated by hbm2java
 */
@Embeddable
public class GlassesId  implements java.io.Serializable {


     private int id;
     private int orderGlassId;
     private int orderGlassBudgetId;
     private int orderGlassBudgetCostumersId;

    public GlassesId() {
    }

    public GlassesId(int id, int orderGlassId, int orderGlassBudgetId, int orderGlassBudgetCostumersId) {
       this.id = id;
       this.orderGlassId = orderGlassId;
       this.orderGlassBudgetId = orderGlassBudgetId;
       this.orderGlassBudgetCostumersId = orderGlassBudgetCostumersId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="orderGlass_id", nullable=false)
    public int getOrderGlassId() {
        return this.orderGlassId;
    }
    
    public void setOrderGlassId(int orderGlassId) {
        this.orderGlassId = orderGlassId;
    }


    @Column(name="orderGlass_budget_id", nullable=false)
    public int getOrderGlassBudgetId() {
        return this.orderGlassBudgetId;
    }
    
    public void setOrderGlassBudgetId(int orderGlassBudgetId) {
        this.orderGlassBudgetId = orderGlassBudgetId;
    }


    @Column(name="orderGlass_budget_costumers_id", nullable=false)
    public int getOrderGlassBudgetCostumersId() {
        return this.orderGlassBudgetCostumersId;
    }
    
    public void setOrderGlassBudgetCostumersId(int orderGlassBudgetCostumersId) {
        this.orderGlassBudgetCostumersId = orderGlassBudgetCostumersId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GlassesId) ) return false;
		 GlassesId castOther = ( GlassesId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getOrderGlassId()==castOther.getOrderGlassId())
 && (this.getOrderGlassBudgetId()==castOther.getOrderGlassBudgetId())
 && (this.getOrderGlassBudgetCostumersId()==castOther.getOrderGlassBudgetCostumersId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getOrderGlassId();
         result = 37 * result + this.getOrderGlassBudgetId();
         result = 37 * result + this.getOrderGlassBudgetCostumersId();
         return result;
   }   


}


