package com.jotase.crystalsystem.models;
// Generated Jul 4, 2015 1:37:22 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderglassId generated by hbm2java
 */
@Embeddable
public class OrderglassId  implements java.io.Serializable {


     private int id;
     private int budgetId;
     private int budgetCostumersId;

    public OrderglassId() {
    }

    public OrderglassId(int id, int budgetId, int budgetCostumersId) {
       this.id = id;
       this.budgetId = budgetId;
       this.budgetCostumersId = budgetCostumersId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="budget_id", nullable=false)
    public int getBudgetId() {
        return this.budgetId;
    }
    
    public void setBudgetId(int budgetId) {
        this.budgetId = budgetId;
    }


    @Column(name="budget_costumers_id", nullable=false)
    public int getBudgetCostumersId() {
        return this.budgetCostumersId;
    }
    
    public void setBudgetCostumersId(int budgetCostumersId) {
        this.budgetCostumersId = budgetCostumersId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderglassId) ) return false;
		 OrderglassId castOther = ( OrderglassId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getBudgetId()==castOther.getBudgetId())
 && (this.getBudgetCostumersId()==castOther.getBudgetCostumersId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getBudgetId();
         result = 37 * result + this.getBudgetCostumersId();
         return result;
   }   


}


