package com.jotase.crystalsystem.models;
// Generated Jul 15, 2015 1:51:53 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderglassHasServiceId generated by hbm2java
 */
@Embeddable
public class OrderglassHasServiceId  implements java.io.Serializable {


     private int orderGlassId;
     private int orderGlassBudgetId;
     private int orderGlassBudgetCostumersId;
     private int serviceId;

    public OrderglassHasServiceId() {
    }

    public OrderglassHasServiceId(int orderGlassId, int orderGlassBudgetId, int orderGlassBudgetCostumersId, int serviceId) {
       this.orderGlassId = orderGlassId;
       this.orderGlassBudgetId = orderGlassBudgetId;
       this.orderGlassBudgetCostumersId = orderGlassBudgetCostumersId;
       this.serviceId = serviceId;
    }
   


    @Column(name="orderGlass_id", nullable=false)
    public int getOrderGlassId() {
        return this.orderGlassId;
    }
    
    public void setOrderGlassId(int orderGlassId) {
        this.orderGlassId = orderGlassId;
    }


    @Column(name="orderGlass_budget_id", nullable=false)
    public int getOrderGlassBudgetId() {
        return this.orderGlassBudgetId;
    }
    
    public void setOrderGlassBudgetId(int orderGlassBudgetId) {
        this.orderGlassBudgetId = orderGlassBudgetId;
    }


    @Column(name="orderGlass_budget_costumers_id", nullable=false)
    public int getOrderGlassBudgetCostumersId() {
        return this.orderGlassBudgetCostumersId;
    }
    
    public void setOrderGlassBudgetCostumersId(int orderGlassBudgetCostumersId) {
        this.orderGlassBudgetCostumersId = orderGlassBudgetCostumersId;
    }


    @Column(name="service_id", nullable=false)
    public int getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(int serviceId) {
        this.serviceId = serviceId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderglassHasServiceId) ) return false;
		 OrderglassHasServiceId castOther = ( OrderglassHasServiceId ) other; 
         
		 return (this.getOrderGlassId()==castOther.getOrderGlassId())
 && (this.getOrderGlassBudgetId()==castOther.getOrderGlassBudgetId())
 && (this.getOrderGlassBudgetCostumersId()==castOther.getOrderGlassBudgetCostumersId())
 && (this.getServiceId()==castOther.getServiceId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderGlassId();
         result = 37 * result + this.getOrderGlassBudgetId();
         result = 37 * result + this.getOrderGlassBudgetCostumersId();
         result = 37 * result + this.getServiceId();
         return result;
   }   


}


