package com.jotase.crystalsystem.models;
// Generated Jul 15, 2015 1:51:53 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderglassHasService generated by hbm2java
 */
@Entity
@Table(name="orderglass_has_service"
    ,catalog="cristal"
)
public class OrderglassHasService  implements java.io.Serializable {


     private OrderglassHasServiceId id;
     private Orderglass orderglass;
     private Service service;
     private Integer qty;
     private Double cost;

    public OrderglassHasService() {
    }

	
    public OrderglassHasService(OrderglassHasServiceId id, Orderglass orderglass, Service service) {
        this.id = id;
        this.orderglass = orderglass;
        this.service = service;
    }
    public OrderglassHasService(OrderglassHasServiceId id, Orderglass orderglass, Service service, Integer qty, Double cost) {
       this.id = id;
       this.orderglass = orderglass;
       this.service = service;
       this.qty = qty;
       this.cost = cost;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orderGlassId", column=@Column(name="orderGlass_id", nullable=false) ), 
        @AttributeOverride(name="orderGlassBudgetId", column=@Column(name="orderGlass_budget_id", nullable=false) ), 
        @AttributeOverride(name="orderGlassBudgetCostumersId", column=@Column(name="orderGlass_budget_costumers_id", nullable=false) ), 
        @AttributeOverride(name="serviceId", column=@Column(name="service_id", nullable=false) ) } )
    public OrderglassHasServiceId getId() {
        return this.id;
    }
    
    public void setId(OrderglassHasServiceId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="orderGlass_id", referencedColumnName="id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="orderGlass_budget_id", referencedColumnName="budget_id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="orderGlass_budget_costumers_id", referencedColumnName="budget_costumers_id", nullable=false, insertable=false, updatable=false) } )
    public Orderglass getOrderglass() {
        return this.orderglass;
    }
    
    public void setOrderglass(Orderglass orderglass) {
        this.orderglass = orderglass;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="service_id", nullable=false, insertable=false, updatable=false)
    public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }

    
    @Column(name="qty")
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    
    @Column(name="cost", precision=22, scale=0)
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }




}


