package com.jotase.crystalsystem.models;
// Generated Jul 15, 2015 1:51:53 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReplacementId generated by hbm2java
 */
@Embeddable
public class ReplacementId  implements java.io.Serializable {


     private int id;
     private int glassesId;
     private int glassesOrderGlassId;
     private int glassesOrderGlassBudgetId;
     private int glassesOrderGlassBudgetCostumersId;

    public ReplacementId() {
    }

    public ReplacementId(int id, int glassesId, int glassesOrderGlassId, int glassesOrderGlassBudgetId, int glassesOrderGlassBudgetCostumersId) {
       this.id = id;
       this.glassesId = glassesId;
       this.glassesOrderGlassId = glassesOrderGlassId;
       this.glassesOrderGlassBudgetId = glassesOrderGlassBudgetId;
       this.glassesOrderGlassBudgetCostumersId = glassesOrderGlassBudgetCostumersId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="glasses_id", nullable=false)
    public int getGlassesId() {
        return this.glassesId;
    }
    
    public void setGlassesId(int glassesId) {
        this.glassesId = glassesId;
    }


    @Column(name="glasses_orderGlass_id", nullable=false)
    public int getGlassesOrderGlassId() {
        return this.glassesOrderGlassId;
    }
    
    public void setGlassesOrderGlassId(int glassesOrderGlassId) {
        this.glassesOrderGlassId = glassesOrderGlassId;
    }


    @Column(name="glasses_orderGlass_budget_id", nullable=false)
    public int getGlassesOrderGlassBudgetId() {
        return this.glassesOrderGlassBudgetId;
    }
    
    public void setGlassesOrderGlassBudgetId(int glassesOrderGlassBudgetId) {
        this.glassesOrderGlassBudgetId = glassesOrderGlassBudgetId;
    }


    @Column(name="glasses_orderGlass_budget_costumers_id", nullable=false)
    public int getGlassesOrderGlassBudgetCostumersId() {
        return this.glassesOrderGlassBudgetCostumersId;
    }
    
    public void setGlassesOrderGlassBudgetCostumersId(int glassesOrderGlassBudgetCostumersId) {
        this.glassesOrderGlassBudgetCostumersId = glassesOrderGlassBudgetCostumersId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReplacementId) ) return false;
		 ReplacementId castOther = ( ReplacementId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getGlassesId()==castOther.getGlassesId())
 && (this.getGlassesOrderGlassId()==castOther.getGlassesOrderGlassId())
 && (this.getGlassesOrderGlassBudgetId()==castOther.getGlassesOrderGlassBudgetId())
 && (this.getGlassesOrderGlassBudgetCostumersId()==castOther.getGlassesOrderGlassBudgetCostumersId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getGlassesId();
         result = 37 * result + this.getGlassesOrderGlassId();
         result = 37 * result + this.getGlassesOrderGlassBudgetId();
         result = 37 * result + this.getGlassesOrderGlassBudgetCostumersId();
         return result;
   }   


}


